### ISSUE TITLE
systemd Service.Type postomaat != fulgu

### ISSUE THREAD

**Issue by ledgr** [gryphius/postomaat#9]
For systemctl to drop back to shell after starting fuglu you have to provide:
[Service]
Type=forking

For postomaat systemd service definition should contain:
[Service]
Type=simple

Otherwise systemctl successfully starts both services, but keep hanging and waiting for service to fork or something.

**Comment by gryphius** [comment]
I can't reproduce this so far, postomaat starts fine for me with type=forking (on arch linux). However, there are a few things missing in postomaat's startup code, for example, it does not currently support the --pidfile argument like fuglu does. I'll update the code to match fuglu's behaviour

**Comment by gryphius** [comment]
merged fuglu's startupcode to postomaat
